language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.2'
  - hhvm # on Trusty only
  - nightly
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - alecabreralituma2@gmail.com
