language: php
php:
  - '7.2'
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - alecabreralituma2@gmail.com
addons:
  sonarcloud:
    organization: "alexandracabreralituma-github"
before_install:
  - travis_retry composer self-update
  - composer install
script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
